template_type: TF
template_version: 0.12

template_parameters:
  variables:
    process : system
  variable_files:
    ./tf11/tf11_tests-2.jx

tags:
- Org:Engineering
- Team Analyst:ShiftLeftTeam
- env25:Y\tBuzz
